file = open(r"C:\Users\LENOVO\OneDrive\Desktop\Artificizen_Internship\Week 01\Day 05\Data.txt", "r")
text = file.read()
file.close()
lines = text.split("\n")
line_count = len(lines)
words = text.split()
word_count = len(words)
character_count = len(text)
print("Number of Lines:", line_count)
print("Number of Words:", word_count)
print("Number of Characters:", character_count)